### PR TITLE
Preview fonts in combobox popup.

### PR DESCRIPTION
**Pull request by ueno**
This patch allows user to preview font before applying the settings.
As we discussed on IRC, the behavior is similar to LibO or OOo font selection combobox,

### CODE REVIEW

**Comment by tagoh** [comment]
Two things after tried this patch:
- Once clicking the combobox and pop down the list, the attribute being added in this patch still takes effect. does this mean there was no way to revert it? or a bug?
- This more or less happens on OOo and LibO, and not this patch specific (regardless of how long it takes FWIW) I'm very concerned about the performance issue when opening the fonts list on the combobox. I have no idea to improve it though.

**Comment by ueno** [comment]
For the first thing: did you try the latest commit fe1a3bf98f8437b5bfdc1f0712aee2c098eb201 (I did git rebase...)?  I can no longer reproduce the problem.

For the second, I'm thinking of another option: add a new row under each combobox and put a label showing sample text in it, instead of modifying combobox cells.  This approach will reduce the number of fonts opened at the same time and won't affect performance.

**Comment by ueno** [comment]
Here is a screenshot of the second approach:

font-preview

**Comment by tagoh** [comment]
That looks good to me. though I'm not an UI designer, someone may has another idea for improvements.

**Pull request merged**
